// Action Types
export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';
export const UPDATE_STATE_SUCCESS = 'UPDATE_STATE_SUCCESS';
export const GET_FASTEST_COMPLAINT = 'GET_FASTEST_COMPLAINT';
export const GET_BIRTH_DATA = 'GET_BIRTH_DATA';